works = [
  {
    name: "theTrailers",
    url: "https://thetrailerss.netlify.app/",
    icon: "/img/t.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/trailers.png",
  },
  {
    name: "todoApp",
    url: "https://todos-mock.netlify.app/",
    icon: "/img/bt.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/todo.png",
  },
  {
    name: "Pokemon",
    url: "https://pokemon-gos.netlify.app/",
    icon: "/img/letter.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/pokemons.png",
  },
  {
    name: "Sunnyside",
    url: "https://sunnyside-test.netlify.app",
    icon: "/img/s.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/sunnyside.png",
  },
  {
    name: "Flags",
    url: "https://flags-mock.netlify.app/",
    icon: "/img/f.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/flags.png",
  },
  {
    name: "Shopping List",
    url: "https://shopping-list-practice.netlify.app/",
    icon: "/img/ss.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/lists.png",
  },
  {
    name: "Vetclinics",
    url: "https://vet-clinics.netlify.app/",
    icon: "/img/v.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/vet.png",
  },
  {
    name: "Cofferoasters",
    url: "https://cofferoasters-test.netlify.app/",
    icon: "/img/c.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/coffees.png",
  },
  {
    name: "Logoipsum",
    url: "https://logoipsum-m.netlify.app/",
    icon: "/img/lll.png",
    type: ["API", "Design", "Colors", "Scss"],
    img: "/img/logoipsum.png",
  },
];
